# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor_button.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor_button.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14monitor_button.proto\"C\n\x0b\x42uttonEvent\x12\x1e\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0e.ButtonActions\x12\x14\n\x0ctimeOccurred\x18\x02 \x01(\x01\"!\n\x10\x42uttonPressCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05*\'\n\rButtonActions\x12\t\n\x05PRESS\x10\x00\x12\x0b\n\x07RELEASE\x10\x01\x32H\n\x10\x42uttonMonitoring\x12\x34\n\x11HandleButtonEvent\x12\x0c.ButtonEvent\x1a\x11.ButtonPressCountb\x06proto3'
)

_BUTTONACTIONS = _descriptor.EnumDescriptor(
  name='ButtonActions',
  full_name='ButtonActions',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=128,
  serialized_end=167,
)
_sym_db.RegisterEnumDescriptor(_BUTTONACTIONS)

ButtonActions = enum_type_wrapper.EnumTypeWrapper(_BUTTONACTIONS)
PRESS = 0
RELEASE = 1



_BUTTONEVENT = _descriptor.Descriptor(
  name='ButtonEvent',
  full_name='ButtonEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='ButtonEvent.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeOccurred', full_name='ButtonEvent.timeOccurred', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=91,
)


_BUTTONPRESSCOUNT = _descriptor.Descriptor(
  name='ButtonPressCount',
  full_name='ButtonPressCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='ButtonPressCount.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=126,
)

_BUTTONEVENT.fields_by_name['action'].enum_type = _BUTTONACTIONS
DESCRIPTOR.message_types_by_name['ButtonEvent'] = _BUTTONEVENT
DESCRIPTOR.message_types_by_name['ButtonPressCount'] = _BUTTONPRESSCOUNT
DESCRIPTOR.enum_types_by_name['ButtonActions'] = _BUTTONACTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonEvent = _reflection.GeneratedProtocolMessageType('ButtonEvent', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONEVENT,
  '__module__' : 'monitor_button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonEvent)
  })
_sym_db.RegisterMessage(ButtonEvent)

ButtonPressCount = _reflection.GeneratedProtocolMessageType('ButtonPressCount', (_message.Message,), {
  'DESCRIPTOR' : _BUTTONPRESSCOUNT,
  '__module__' : 'monitor_button_pb2'
  # @@protoc_insertion_point(class_scope:ButtonPressCount)
  })
_sym_db.RegisterMessage(ButtonPressCount)



_BUTTONMONITORING = _descriptor.ServiceDescriptor(
  name='ButtonMonitoring',
  full_name='ButtonMonitoring',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=169,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleButtonEvent',
    full_name='ButtonMonitoring.HandleButtonEvent',
    index=0,
    containing_service=None,
    input_type=_BUTTONEVENT,
    output_type=_BUTTONPRESSCOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUTTONMONITORING)

DESCRIPTOR.services_by_name['ButtonMonitoring'] = _BUTTONMONITORING

# @@protoc_insertion_point(module_scope)
