# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import send_keypresses_pb2 as send__keypresses__pb2


class KeySenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleKeyEvent = channel.unary_unary(
                '/KeySender/HandleKeyEvent',
                request_serializer=send__keypresses__pb2.KeysPressed.SerializeToString,
                response_deserializer=send__keypresses__pb2.Empty.FromString,
                )


class KeySenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleKeyEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeySenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleKeyEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleKeyEvent,
                    request_deserializer=send__keypresses__pb2.KeysPressed.FromString,
                    response_serializer=send__keypresses__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeySender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeySender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleKeyEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeySender/HandleKeyEvent',
            send__keypresses__pb2.KeysPressed.SerializeToString,
            send__keypresses__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
