# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: send_keypresses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='send_keypresses.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15send_keypresses.proto\"\x1b\n\x0bKeysPressed\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\x07\n\x05\x45mpty23\n\tKeySender\x12&\n\x0eHandleKeyEvent\x12\x0c.KeysPressed\x1a\x06.Emptyb\x06proto3'
)




_KEYSPRESSED = _descriptor.Descriptor(
  name='KeysPressed',
  full_name='KeysPressed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='KeysPressed.keys', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['KeysPressed'] = _KEYSPRESSED
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeysPressed = _reflection.GeneratedProtocolMessageType('KeysPressed', (_message.Message,), {
  'DESCRIPTOR' : _KEYSPRESSED,
  '__module__' : 'send_keypresses_pb2'
  # @@protoc_insertion_point(class_scope:KeysPressed)
  })
_sym_db.RegisterMessage(KeysPressed)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'send_keypresses_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)



_KEYSENDER = _descriptor.ServiceDescriptor(
  name='KeySender',
  full_name='KeySender',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=63,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleKeyEvent',
    full_name='KeySender.HandleKeyEvent',
    index=0,
    containing_service=None,
    input_type=_KEYSPRESSED,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYSENDER)

DESCRIPTOR.services_by_name['KeySender'] = _KEYSENDER

# @@protoc_insertion_point(module_scope)
